name: Run tests

on: [push]

jobs:
    test-node:
        name: Test on node ${{ matrix.node_version }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # Source: https://nodejs.org/en/about/releases/#releases
                node_version: ["14", "16", "18", "lts/*", "latest"]
                os: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node_version }}
            - name: Cache module
              uses: actions/cache@v3
              with:
                  path: ~/.npm/
                  key: npm-cache
            - name: Install modules
              run: yarn install
            - name: Run node tests
              run: |
                  npm run test
                  npm run report-coverage
            - name: Send coverage
              uses: codecov/codecov-action@v4
